title: Philipp's and Steffen's personal wiki
author: Philipp
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Intellegibile content that keeps on wandering in
  Philipp's and Steffen's head.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
